#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/sm8650-common

PRODUCT_COPY_FILES += \
    vendor/samsung/sm8650-common/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/samsung/sm8650-common/proprietary/product/etc/permissions/privapp-permissions-euiccgoogle.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-euiccgoogle.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/DsgpPolicy.csv:$(TARGET_COPY_OUT_VENDOR)/etc/DsgpPolicy.csv \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/config/PCC_Config-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/config/PCC_Config-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/config/pcc_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/aip/config/pcc_config.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/1129_dummy_1441_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/1129_dummy_1441_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/CIGSOL_SWISP_200M_v1.6.2_Exp18_e12850_592x4176_A16W8_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/CIGSOL_SWISP_200M_v1.6.2_Exp18_e12850_592x4176_A16W8_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/CIGSOL_fp32_ver220923_HTP_FP16_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/CIGSOL_fp32_ver220923_HTP_FP16_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet2_AIMFISP-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet2_AIMFISP-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet2_eraw_AIMFISP-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet2_eraw_AIMFISP-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet_AIMFISP-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet_AIMFISP-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet_AISR-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet_AISR-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet_eraw_AIMFISP-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet_eraw_AIMFISP-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/ModelSet_v-timestamp:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/ModelSet_v-timestamp \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_1x_C2C_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_1x_C2C_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_1x_T2C_Indoor_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_1x_T2C_Indoor_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_1x_T2C_Outdoor_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_1x_T2C_Outdoor_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_1x_ll_C2C_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_1x_ll_C2C_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_2x_C2C_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_2x_C2C_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_2x_ll_C2C_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_2x_ll_C2C_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/aiisp_4x_C2C_cached.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/aiisp_4x_C2C_cached.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_eraw_model_mf_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_eraw_model_mf_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_eraw_model_nl_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_eraw_model_nl_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_model_ll_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_model_ll_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_model_mf_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_model_mf_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_model_nl_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_model_nl_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_tmodel_ll_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_tmodel_ll_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/aip/model/mfisp_tmodel_nl_Tetra_RGB_fp16.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/aip/model/mfisp_tmodel_nl_Tetra_RGB_fp16.dlc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_haptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_haptic.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_sec.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_spatializer.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_policy_configuration_base.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_base.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/beauty/settings.dat:$(TARGET_COPY_OUT_VENDOR)/etc/beauty/settings.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/btcon.json:$(TARGET_COPY_OUT_VENDOR)/etc/btcon.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/nicm_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/nicm_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/tlpd_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/tlpd_oem_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/external_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/external_camera_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/hqm_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hqm_device.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gnss-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-aidl-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-spu-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/camera.unihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camera.unihal.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.audio.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.audio.samsung.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qccvendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qccvendor.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.wlan.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.wlan.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qms.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qms.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/samsung.software.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.software.media.c2@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/tlpd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tlpd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/trusteduilistener.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusteduilistener.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.secureprocessor@1.0.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui-aidl-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.smp2p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.smp2p.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.ifaa-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.ifaa-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.security.widevine.keyprov-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.security.widevine.keyprov-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal-default.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.rilchip.qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.qcom.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/wifi_qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_qcom.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/wifi_sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_sec.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libuwb-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libuwb-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_performance_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_performance_pineapple_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_pineapple_vendor.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_pineapple_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_pineapple_vendor.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_pineapple/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_pineapple/video_system_specs.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mem_logger_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mem_logger_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mercury.json:$(TARGET_COPY_OUT_VENDOR)/etc/mercury.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mercury_hv.json:$(TARGET_COPY_OUT_VENDOR)/etc/mercury_hv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/environment.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/environment.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_chn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_chn.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/portrait_data/SRIB_ClatNetLite_INT8_V004_sm8650_vendor.tvm.so:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/SRIB_ClatNetLite_INT8_V004_sm8650_vendor.tvm.so \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/portrait_data/dual_portrait_product.json:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/dual_portrait_product.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/portrait_data/single_bokeh_feature_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/single_bokeh_feature_vendor.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/qms_log_config:$(TARGET_COPY_OUT_VENDOR)/etc/qms_log_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sat/arcsat_fusion.config:$(TARGET_COPY_OUT_VENDOR)/etc/sat/arcsat_fusion.config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config_oem:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config_oem \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-edgnss-daemon.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-qsap-location.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-qsap-location.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qms.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qms.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-base-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-base-policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/samsung.software.media.c2-ext-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/samsung.software.media.c2-ext-policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_default_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors_template.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_irq.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_power_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qrd_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qrd_tmd2755_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qsh_ble_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_4.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/str/str_preference_data.dat:$(TARGET_COPY_OUT_VENDOR)/etc/str/str_preference_data.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/kiwi_v2/WCNSS_qcom_cfg.ini \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/nfc/libsn300u_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libsn300u_fw.so \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/AIAwbModelFront_v1.0.tflite:$(TARGET_COPY_OUT_VENDOR)/lib64/AIAwbModelFront_v1.0.tflite \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/AIAwbModel_v2.3.tflite:$(TARGET_COPY_OUT_VENDOR)/lib64/AIAwbModel_v2.3.tflite \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/bitmlconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/camxfl115indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl115indices.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/camxfl300v1indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v1indices.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/camxfl300v2indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v2indices.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/camxflcustom300indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxflcustom300indices.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_lsi_s5khp2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_lsi_s5khp2.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.12_lsi_s5k3lu_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.12_lsi_s5k3lu_full.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_lsi_s5k3lu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_lsi_s5k3lu.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_sony_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_sony_imx564.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.3_sony_imx754_x3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.3_sony_imx754_x3.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.6_sony_imx754_x10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.6_sony_imx754_x10.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.sensormodule.6_sony_imx854.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.6_sony_imx854.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5khp2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5khp2.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx564.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx754.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx754.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx854.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx854.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/multical_param.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/multical_param.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/t2_w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t2_w_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/t_t10_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_t10_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/p3_profile.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/p3_profile.bin

PRODUCT_PACKAGES += \
    vendor.samsung.hardware.security.widevine.keyprov-V2-ndk \
    SWPD_libTsAf \
    btaudio_offload_if \
    camera.device-external-impl \
    com.samsung.ois.mcu_stm32g \
    com.samsung.sensor.hi1337 \
    com.samsung.sensor.hi847 \
    com.samsung.sensor.imx258 \
    com.samsung.sensor.imx374 \
    com.samsung.sensor.imx471 \
    com.samsung.sensor.imx564 \
    com.samsung.sensor.imx596 \
    com.samsung.sensor.imx754 \
    com.samsung.sensor.imx854 \
    com.samsung.sensor.s5k3j1 \
    com.samsung.sensor.s5k3k1 \
    com.samsung.sensor.s5k3lu \
    com.samsung.sensor.s5kgn3 \
    com.samsung.sensor.s5khp2 \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.hwcfg.bps \
    com.qti.hwcfg.ife \
    com.qti.hwcfg.ipe \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.evadepth \
    com.qti.node.evs \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.itofpreprocess \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afc \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbr \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.roimixer \
    com.qti.stats.roimixerlib \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.samsung.node.capture_fusion \
    com.samsung.node.realtimebokeh \
    com.samsung.node.resolution \
    com.samsung.node.smooth_transition \
    com.samsung.node.uniplugin_binning \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_record_portrait_depth_extract \
    com.samsung.node.uniplugin_record_portrait_render \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    com.ss.hwcfg.bps \
    com.ss.hwcfg.ife \
    com.ss.hwcfg.ipe \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libTsAeFront_e3 \
    libTsAe_e3 \
    libcamxevainterface \
    libdepthmapwrapper_itof \
    libdepthmapwrapper_secure \
    camx.device-impl \
    camx.provider-impl \
    cdsp_face \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8650 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    android.hardware.gnss-aidl-impl-qti \
    audio.primary.pineapple \
    camera.qcom.sm8650 \
    camera.qcom \
    camera.unihal.default \
    com.qti.chi.offline \
    com.qti.chi.override \
    gatekeeper.mdfpp \
    libsecaudiohal_aidl \
    libspuqtigatekeeper \
    vendor.qti.hardware.bttpi-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.samsung.hardware.audio@1.0-impl \
    vendor.samsung.hardware.gnss-aidl-impl-sec \
    vulkan.adreno \
    libAIHighRes_interface \
    libAIMFISP.camera.samsung \
    libAIMFISP_core.camera.samsung \
    libAISR_core.camera.samsung \
    libAISegmenter_v2.camera.samsung \
    libAImode_wrapper.camera.samsung \
    libAIphoto_core.camera.samsung \
    libAfHelper.uniplugin@1.0 \
    libAlacSwDec \
    libApeSwDec \
    libBarcodeReader.vendor.quram \
    libBeauty_v4.camera.samsung \
    libBlurDetectionDeepLearning.camera.samsung \
    libCB \
    libDLInterface.camera.samsung \
    libDepthPortraitVideo_interface \
    libDeviceInfoProvider \
    libDocumentDetector.uniplugin@1.0 \
    libEventFinder.camera.samsung \
    libEvrcSwCodec \
    libFace_Landmark_API.camera.samsung \
    libFace_Landmark_Engine.camera.samsung \
    libFastUWDistortionCorrection.camera.samsung \
    libFlacSwDec \
    libFrucSSMLib \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libHDRVerifier_v1.camera.samsung \
    libHandGesture.camera.samsung \
    libHprFace_GAE_api.camera.samsung \
    libHprVisualEffect \
    libHpr_RecFace_dl_v1.0.camera.samsung \
    libHpr_RecGAE_cvFeature_v1.0.camera.samsung \
    libHumanSegVideoModel_Vendor \
    libIDDQD_core \
    libIMUSensor \
    libIfaaCa \
    libLightObjectDetector_v1.camera.samsung \
    libLocalTM_capture_core.camera.samsung \
    libLocalTM_preview_core \
    libLocalTM_wrapper.camera.samsung \
    libMoireDetection.camera.samsung \
    libMoireDetectionWrapper.camera.samsung \
    libMoireDetector.uniplugin@1.0 \
    libMoonVerifier_v1.camera.samsung \
    libMotionEstimator.camera.samsung \
    libMotionEstimator.uniplugin@1.0 \
    libMotionEstimatorWrapper.camera.samsung \
    libObjectDetector.uniplugin@1.0 \
    libOpenCL \
    libOpenCL_adreno \
    libOpenCv.camera.samsung \
    libPanDetector \
    libPdSdCore \
    libPeripheralStateUtils \
    libPersonal_capture.camera.samsung \
    libPersonal_core.camera.samsung \
    libPetDetector_interface \
    libPetDetector_v1.camera.samsung \
    libPortraitDistortionCorrection.arcsoft \
    libPortraitDistortionCorrectionCali.arcsoft \
    libPortraitSolution.camera.samsung_preview \
    libQRInterface.camera.samsung \
    libQSEEComAPI \
    libQcelp13SwCodec \
    libQrDetector.uniplugin@1.0 \
    libRelighting_API.camera.samsung \
    libRenderPortraitVideo_interface \
    libSNPE \
    libSRIB_ARVL_HAP.camera.samsung \
    libSWB.camera.samsung \
    libSWNDFilterPreview.camera.samsung \
    libSceneDetector_v1.camera.samsung \
    libSecC2ComponentStore \
    libSecExif.uniplugin@1.0 \
    libSecJpegEncoder.uniplugin@1.0 \
    libSecPhotoHdrEncoder.uniplugin@1.0 \
    libSmartScan.camera.samsung \
    libSnpeCpu \
    libSnpeGpu \
    libSnpeHtpV75Stub \
    libTetraMFP10.camera.samsung \
    libTetraMFP10Tuning.camera.samsung \
    libTetraSR10.camera.samsung \
    libTetraSR10Tuning.camera.samsung \
    libTouchInputVM \
    libTrustedInput \
    libTrustedInputAIDL \
    libTrustedInputTZ \
    libTrustedInputUtils \
    libTrustedUI \
    libTrustedUIAIDL \
    libTrustedUITZ \
    libTrustedUIVM \
    libTsAf_E123Q \
    libTsAwbFront_E123 \
    libTsAwb_E3 \
    libTxPwrJni \
    libUltraWideDistortionCorrection.camera.samsung \
    libUltraWideDistortionCorrection.uniplugin@1.0 \
    libUniPluginUtils \
    libUniScaler.uniplugin@1.0 \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    libVoiceSdk \
    libWideDistortionCorrection.camera.samsung \
    lib_SamsungRec_08020 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_play_plus_ver800 \
    lib_SoundBooster_ver2000 \
    lib_lvacfs \
    lib_profiler \
    libadm \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagm \
    libagm_compress_plugin \
    libagm_mixer_plugin \
    libagm_pcm_plugin \
    libagmclient \
    libagmmixer \
    libai_denoiser_interface \
    libaidenoiser \
    libaidenoiserv2 \
    libaifrc.quram \
    libaivideocentral.arcsoft \
    libar-acdb \
    libar-gpr \
    libar-gsl \
    libar-pal \
    libarcsoft_aieffectpk_detection \
    libarcsoft_aieffectpk_dualcam_video_bokeh \
    libarcsoft_aieffectpk_video \
    libarcsoft_aieffectpk_video_bokeh \
    libarcsoft_aieffectpk_video_depth \
    libarcsoft_aieffectpk_video_effect \
    libarcsoft_aieffectpk_video_plight \
    libarcsoft_aiscenedetection \
    libarcsoft_deflicker_native \
    libarcsoft_dualcam_portraitlighting_preview \
    libarcsoft_object_tracking \
    libarmemlog \
    libatccore \
    libats \
    libaudio_log_utils \
    libaudiochargerlistener \
    libaudiofeaturestats \
    libauto_framing_arcsoft.uniplugin@1.0 \
    libauto_framing_lite.uniplugin@1.0 \
    libautoframing_object_tracker.camera.samsung \
    libautotracking_interface \
    libbacklight-calib \
    libbatching \
    libbeauty_preview.uniplugin@1.0 \
    libbeautyshot.arcsoft \
    libbitmlengine \
    libbitmlenginev2 \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbodyid.arcsoft \
    libbt-hidlclient \
    libbtnv \
    libc++_shared \
    libc2filterplugin \
    libcamera2ndk_vendor \
    libcamerapostproc \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncsdatafactory \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2udk7vendor \
    libcapiv2uvvendor \
    libcdfw \
    libcdsp_default_listener \
    libcdsprpc \
    libchifeature2 \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libcom.qti.chinodeutils \
    libcommonchiutils \
    libconfigdb \
    libcpion \
    libcv_common \
    libdataitems \
    libdiag \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplaydebug \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libdsd2pcm \
    libdsi_netctrl \
    libdsmanager \
    libdsutils \
    libdualcam_refocus_video \
    libengine_did \
    libengmode_client \
    libese-grdg \
    libeva \
    libeva_util \
    libevent_finder.uniplugin@1.0 \
    libexifa.camera.samsung \
    libface_landmark.arcsoft \
    libfast_uwdc.uniplugin@1.0 \
    libfastcvdsp_stub \
    libfastcvopt \
    libfeutils \
    libfloatingfeature \
    libfloatingfeature_hal \
    libfocuspeaking \
    libfocuspeaking.uniplugin@1.0 \
    libformatConverter.unifunc \
    libgame_enhance \
    libgaya \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpt \
    libgpudataproducer \
    libgralloc_helper.unifunc \
    libgsl \
    libhand_interaction.uniplugin@1.0 \
    libhandgesture.arcsoft \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdradaptivecustom \
    libhdraid.gpu.arcsoft \
    libhdraid.npu.arcsoft \
    libhdrdynamic \
    libhdrdynamicootf \
    libheifcapture \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhistogram \
    libhme \
    libhwvault \
    libhypermotion_core \
    libhypermotion_interface \
    libiddqd.uniplugin@1.0 \
    libidl \
    libimage_enhancement.arcsoft \
    libimagecodec_native.quram \
    libimgproc_sw.unifunc@common \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libizat_client_api \
    libizat_core \
    libjpegQtable_interface \
    libjpege \
    libjpegencoder_sw.unifunc \
    libjpegsq.media.samsung \
    libjump_shot.uniplugin@1.0 \
    libkcl \
    libkernelmanager \
    liblbs_core \
    liblistensoundmodel2vendor \
    liblivefocus_preview_engine \
    liblivefocus_preview_interface \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_core \
    libloc_mq_client \
    libloc_socket \
    libloc_util \
    liblocaltm_capture.uniplugin@1.0 \
    liblocaltm_preview.uniplugin@1.0 \
    liblocation_api \
    liblocation_api_msg \
    liblocation_client_api \
    liblocation_integration_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    liblx-ar_util \
    liblx-osal \
    libmaskdetection.uniplugin@1.0 \
    libmcaimegpu.samsung \
    libmctfengine_stub \
    libmdmdetect \
    libmdsprpc \
    libmemutils \
    libmfGhostDetection \
    libmfec \
    libminkdescriptor \
    libminksocket_vendor \
    libmm-hdcpmgr \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmosal_vendor \
    libmpbase \
    libmulticam_image_optical_zoom \
    libmulticam_optical_zoom_control \
    libmulticam_video_optical_zoom \
    libmultiobject_tracker \
    libnanopb \
    libndfilter_preview.uniplugin@1.0 \
    libnicm \
    libnicm_dsi \
    libnicm_utils \
    liboemcrypto \
    libopencv \
    libopencv3a \
    libopestriping \
    libops \
    libos \
    libpadm \
    libpal_net_if \
    libpantilt_detector.uniplugin@1.0 \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpersonalimprinting.uniplugin@1.0 \
    libpet_detector.uniplugin@1.0 \
    libpetcamera_engine \
    libphotohdr \
    libpredeflicker_native \
    libprofileparamstorage \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_hwaudiocodec \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqcbor \
    libqcc_file_agent \
    libqcc_sdk \
    libqcci_legacy \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_platform \
    libqcodec2_streaminteg_filter \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdutils \
    libqesdk2_0 \
    libqfp_sensortest \
    libqisl \
    libqll \
    libqll10 \
    libqllengine \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsegnet \
    libqservice \
    libqsh \
    libqshcamera \
    libqsocket \
    libqspm-mem-utils-vendor \
    libqtigefar \
    librapidscorerplus \
    librcmask \
    librechdr10plus.sec \
    librechdr10plus \
    librecordalive \
    libril_sem \
    librmengine_plus.uniplugin@1.0 \
    librpmb \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsavscmn \
    libscaler_hw.unifunc \
    libscaler_sw.unifunc \
    libscenedetector.uniplugin@1.0 \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmdal \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsdynatm \
    libsec-ril-impl \
    libsec2imageformatfilter \
    libsec_esek \
    libsec_semHalTlc \
    libsec_semRil \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecfr_engine \
    libsecfr_model \
    libsecnativefeature \
    libsecril-client_vendor \
    libsecsettingsmanager \
    libsegmentationeffect.uniplugin@1.0 \
    libsegmentationeffect_capture.uniplugin@1.0 \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsensorlistener \
    libsensorndkbridge \
    libsensorslog \
    libsfeShiftExtrapolation \
    libsfp_sensor \
    libsfp_teegw \
    libsgutils2 \
    libshctrl \
    libshotsuggestion \
    libshotsuggestion_engines \
    libshsc \
    libsi \
    libsimba.media.samsung \
    libsingle_portrait_preview.uniplugin@1.0 \
    libskeymint10device \
    libskeymint_cli \
    libsmartfocus.uniplugin@1.0 \
    libsnap_compute \
    libsnap_compute_wrapper \
    libsnap_qnn \
    libsnap_vndk \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsnaplite_native \
    libsnaplite_wrapper \
    libsndcardparser \
    libsnpe_dsp_domains_v3 \
    libsnpe_wrapper \
    libsns_api \
    libsns_direct_channel_stub \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsoc_helper \
    libsocial_image_enhancement.uniplugin@1.0 \
    libspatializerparamstorage \
    libspcom \
    libspeakercalibration \
    libspictrl \
    libspl \
    libspukeymint \
    libspukeymintdeviceutils \
    libspukeymintutils \
    libsrib_CNNInterface.camera.samsung \
    libsrib_humanaware_engine.camera.samsung \
    libssd \
    libssengine.uniplugin@1.0 \
    libstagefright_foundation_vendor \
    libsubsystem_control \
    libswregistrationalgo \
    libsynergy_loc_api \
    libsynx \
    libsys_info_cache \
    libsysmon_cdsp_skel \
    libtaautoload \
    libtensorflowLite.singletake.camera.samsung \
    libtensorflowlite.camera.samsung \
    libtensorflowlite_c_vendor \
    libtestutils \
    libtfestriping \
    libtflitecore \
    libthermalclient \
    libthirdparty_zoomtranslator_imp \
    libthreadutils \
    libtime_genoff \
    libtinyxml2_1 \
    libtlpd \
    libtlpd_configmgr \
    libtlpd_crypto \
    libtlpd_internal \
    libtlpd_logger \
    libtrustedapploader \
    libtswrappercommon \
    libubifocus \
    libubwcp \
    libunidatamanager \
    libuniplugin \
    libvdis_core \
    libvdis_interface \
    libvicom \
    libvideobeauty.arcsoft \
    libvideobeauty.uniplugin@1.0 \
    libvideobeauty_capture.uniplugin@1.0 \
    libvideobeauty_interface \
    libvideoml \
    libvideotxr \
    libvkmanager_vendor \
    libvmfilexfer \
    libvmmem \
    libvui_dmgr \
    libvui_dmgr_client \
    libwifiobserver \
    libxml \
    libxtadapter \
    libzoomroi.samsung \
    libzoomroi_lite.samsung \
    nfc_nci_nxpsn \
    qti.video.utils.videobufferlayout \
    libSnpeHtpV75Skel \
    libapn_dsp_skel \
    libbitml_nsp_75na_skel \
    libdpp_engine_skel \
    libdspCV_skel \
    libdsphist_qc_skel \
    libdspmc_qc_skel \
    libevadsp \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhdr_skel \
    libqsegnetengine_dsp_skel \
    libscveT2T_skel \
    libworker_pool \
    libQnnHtpV75Skel \
    sensors.flicker \
    sensors.grip \
    sensors.qsh \
    service-listener-ext-aidl-V1-ndk \
    libQnnHtp \
    libQnnHtpV75Stub \
    libQnnSystem \
    libasphere \
    libaudioeffectoffload \
    libaudiosaplus_sec \
    libmyspace \
    libquasar \
    libsamsungSoundbooster_plus \
    libshoebox \
    libswdap \
    libswspatializer \
    unihal_android \
    unihal_cutils \
    unihal_entry \
    unihal_filter_unit \
    unihal_main \
    unihal_scenario \
    unihal_uniplugin@1.0 \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.gnss-V5-ndk \
    vendor.qti.gnss-service \
    vendor.qti.hardware.AGMIPC@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V3-ndk \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom-V1-ndk \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.atfwd-V1-ndk \
    vendor.qti.hardware.secureprocessor.common@1.0-helper \
    vendor.qti.hardware.secureprocessor.common@1.0 \
    vendor.qti.hardware.secureprocessor.config@1.0 \
    vendor.qti.hardware.secureprocessor.device@1.0 \
    vendor.qti.hardware.trustedui-V1-ndk \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.qccvndhal_aidl-V1-ndk \
    vendor.qti.qccvndhal_aidl-halimpl \
    vendor.qti.qesdhal@1.0 \
    vendor.qti.qesdhal@1.1 \
    vendor.qti.qesdhal@1.2 \
    vendor.qti.qesdhal@1.3 \
    vendor.qti.qspmhal-V1-ndk \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.camera.vcc-V2-ndk \
    vendor.samsung.hardware.gnss-V2-ndk_platform \
    vendor.samsung.hardware.hyper-V2-ndk \
    vendor.samsung.hardware.ifaa-V1-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.media.mpp-V5-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.security.widevine.keyprov-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libhme_dsp_skel_so \
    libmmosal \
    libmmparser_lite \
    com.google.android.widevine.nonupdatable \
    TimeService \
    EuiccGoogle \
    uimservicelibrary \
    android.hardware.gnss-aidl-service-qti.xml \
    atfwd-saidl.xml \
    bttpi-saidl.xml \
    qms-saidl.xml \
    sec_c2_manifest_default0_1_2.xml \
    secaudiohalaidl_manifest.xml \
    vendor.qti.camera.aon-impl.xml \
    vendor.qti.camera.offlinecamera-impl.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss-service.xml \
    vendor.qti.hardware.qseecom@1.0-service.xml \
    vendor.qti.hardware.trustedui-aidl-service.xml \
    vendor.qti.qccvndhal_aidl-service.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.ifaa-service.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.security.widevine.keyprov-service.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    vendor.samsung.hardware.thermal-default.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    audioadsprpcd \
    cdsprpcd \
    cnss-daemon \
    diag-router \
    dspservice \
    factory.ssc \
    hermesd \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.gatekeeper-service \
    android.hardware.gnss-aidl-service-qti \
    android.hardware.security.keymint-service-qti \
    android.hardware.security.keymint-service-spu-qti \
    macloader \
    rild \
    samsung.software.media.c2@1.0-service \
    secaudiohalaidl \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.secureprocessor@1.0 \
    vendor.qti.hardware.trustedui-aidl-service-qti \
    vendor.qti.hardware.trustedui@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.ifaa-service \
    vendor.samsung.hardware.security.widevine.keyprov-service \
    vendor.samsung.hardware.thermal-service \
    init.kernel.post_boot-pineapple \
    init.kernel.post_boot \
    init.qcom.class_core \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    init.qti.time.daemon \
    init.qti.write \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    pd-mapper \
    pm-proxy \
    pm-service \
    ppd \
    qcc-vendor \
    qcom-system-daemon \
    qdcmss \
    qms \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qwesd \
    rmt_storage \
    sec_nvm \
    shsusrd \
    spdaemon \
    sscrpcd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    system_dlkm_modprobe \
    tftp_server \
    time_daemon \
    tlpd \
    trusteduilistener \
    ubwcconvert \
    vendor_modprobe \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
